services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - test-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - test-network

  php-fpm:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: php-fpm
    environment:
      DB_HOST: postgres
      DB_DATABASE: testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpass
    volumes:
      - ./app:/var/www/html
    networks:
      - test-network
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - test-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    environment:
      - SCRAPE_URI=http://nginx:80/nginx_status
      - NGINX_RETRIES=10
    networks:
      - test-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - test-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - test-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  test-network:
